//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Yom.Lib.Data.EF
{
    public partial class Item
    {
        public long Id { get; set; }
        public short Type { get; set; }
        public long UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual OweItem OweItem { get; set; }
    }
    
}
